/**
 * scanCoachStaticContent.ts
 *
 * Static text content for all ScanCoach views, keyed by "module:viewId".
 * Used by the ScanCoach editor to pre-populate fields when no DB override
 * exists yet — so admins can see and edit the current default content.
 *
 * Only text fields are stored here (description, howToGet, tips, pitfalls,
 * structures, measurements, criticalFindings). Image URLs and SVG probe
 * diagrams remain in the original ScanCoach page files.
 */

export interface StaticViewContent {
  description?: string;
  howToGet?: string[];
  structures?: string[];
  tips?: string[];
  pitfalls?: string[];
  measurements?: string[];
  criticalFindings?: string[];
}

/** Map key: "${module}:${viewId}" */
const STATIC_CONTENT: Record<string, StaticViewContent> = {
  // ─── Adult TTE ──────────────────────────────────────────────────────────────
  "tte:plax": {
    description: "The standard starting view for a TTE exam. Obtained from the left parasternal window with the probe in the 3rd–4th intercostal space, left sternal border. The long axis of the heart is displayed with the aortic root on the right and the LV apex pointing to the left.",
    structures: ["Aortic valve", "Mitral valve", "LV", "LA", "LVOT", "Descending aorta (posterior)"],
    howToGet: ["Position probe at 3rd–4th ICS, left sternal border", "Marker dot toward right shoulder (2 o'clock)", "Tilt probe to open up LVOT — IVS should be horizontal", "Adjust depth to include descending aorta posteriorly"],
    tips: ["Tilt probe to open up LVOT — IVS should be horizontal", "Descending aorta posterior to MV confirms true PLAX"],
    pitfalls: ["Foreshortening underestimates LV size", "Descending aorta mistaken for LA"],
    measurements: ["LVID (d/s)", "IVS (d)", "PW (d)", "Ao root", "LA diameter", "LVOT diameter"],
  },
  "tte:psax_av": {
    description: "Obtained by rotating the probe 90° clockwise from PLAX. Shows the aortic valve in cross-section ('Mercedes-Benz' sign for tricuspid AV), RVOT, pulmonary valve, and interatrial septum.",
    structures: ["Aortic valve (3 cusps)", "RVOT", "Pulmonary valve", "LA", "RA", "Tricuspid valve", "Interatrial septum"],
    howToGet: ["From PLAX, rotate probe 90° clockwise", "Marker dot toward left shoulder", "Tilt slightly to bring AV into circular cross-section"],
    tips: ["'Mercedes-Benz' sign = normal tricuspid AV", "Bicuspid AV: 2 cusps, fish-mouth opening", "Assess for ASD at this level"],
    pitfalls: ["Bicuspid AV may appear tricuspid if not fully open", "RVOT foreshortening"],
    measurements: ["RVOT diameter", "Pulmonary valve annulus", "AV planimetry (AVA)"],
  },
  "tte:psax_mv": {
    description: "Obtained by tilting the probe slightly inferiorly from PSAX AV level. Shows the mitral valve in cross-section ('fish-mouth' appearance). Used for MV planimetry in mitral stenosis and regional wall motion assessment.",
    structures: ["Mitral valve (fish-mouth)", "LV (circular)", "Papillary muscles"],
    howToGet: ["From PSAX AV, tilt probe inferiorly", "Mitral valve should appear as 'fish-mouth' opening", "Both leaflets should open symmetrically"],
    tips: ["Fish-mouth opening of MV — both leaflets should open symmetrically", "Identify A1/A2/A3 and P1/P2/P3 scallops for MR localization", "Planimetry of MVA in mitral stenosis"],
    pitfalls: ["Oblique cut gives oval LV — reposition for true circle", "Papillary muscle level vs MV level"],
    measurements: ["MVA planimetry", "LV short-axis dimensions"],
  },
  "tte:psax_pm": {
    description: "Obtained by tilting the probe further inferiorly from PSAX MV level. Shows both papillary muscles and 6 LV wall segments. Best view for regional wall motion assessment.",
    structures: ["LV (circular)", "Anterolateral papillary muscle", "Posteromedial papillary muscle"],
    howToGet: ["From PSAX MV, tilt probe further inferiorly", "Both papillary muscles should be visible", "LV should appear circular"],
    tips: ["Best level for regional wall motion assessment (6 segments visible)", "Anterolateral PM: LAD + LCx territory; Posteromedial PM: RCA territory", "Compare systolic thickening anterior vs inferior walls for ischemia"],
    pitfalls: ["Foreshortening makes LV appear oval", "Near-field artifact from ribs"],
    measurements: ["LV EF (visual)", "Wall motion score"],
  },
  "tte:a4c": {
    description: "The most comprehensive single view in TTE. Obtained from the cardiac apex with the probe marker pointing toward the left shoulder. Shows all four chambers, both AV valves, and the IVS simultaneously.",
    structures: ["LV", "RV", "LA", "RA", "Mitral valve", "Tricuspid valve", "Interatrial septum", "IVS"],
    howToGet: ["Position probe at cardiac apex (5th ICS, MCL)", "Marker dot toward left shoulder (3 o'clock)", "Rotate patient to left lateral decubitus", "Apex must be at TOP of image"],
    tips: ["Apex must be at TOP of image — rotate patient to left lateral decubitus", "Foreshortening: LV appears round — move probe laterally and/or use lower ICS", "RV should be smaller than LV; RV:LV ratio >0.6 suggests RV dilation"],
    pitfalls: ["Foreshortening is the most common error", "Apex not at top → incorrect volumes"],
    measurements: ["LV volumes (biplane Simpson)", "EF", "GLS", "E, A, DT", "e' septal/lateral", "TAPSE", "RV FAC"],
  },
  "tte:a5c": {
    description: "Obtained by tilting the probe anteriorly from A4C. Brings the LVOT and aortic valve into view. Essential for LVOT VTI measurement and aortic valve assessment.",
    structures: ["LV", "RV", "LA", "RA", "LVOT", "Aortic valve", "Mitral valve", "Tricuspid valve"],
    howToGet: ["From A4C, tilt probe anteriorly (toward sternum)", "LVOT and AV come into view between the two ventricles", "Align PW Doppler cursor parallel to LVOT flow"],
    tips: ["Tilt probe anteriorly from A4C until LVOT and AV come into view", "Ideal for PW Doppler in LVOT — align cursor parallel to LVOT flow", "CW through AV for peak and mean gradients", "Color Doppler to assess AR and AS"],
    pitfalls: ["Over-tilting anteriorly loses the 4-chamber view — find the balance", "Underalignment of Doppler cursor underestimates VTI"],
    measurements: ["LVOT VTI", "AV peak/mean gradient", "AVA (continuity equation)"],
  },
  "tte:a2c": {
    description: "Obtained by rotating the probe ~60° counterclockwise from A4C. Shows only the LV and LA (no RV). Provides the anterior and inferior LV walls for biplane EF calculation.",
    structures: ["LV (anterior and inferior walls)", "LA", "Mitral valve", "LAA"],
    howToGet: ["From A4C, rotate probe ~60° counterclockwise", "RV should disappear — only LV and LA visible", "Anterior wall at top, inferior wall at bottom"],
    tips: ["Rotate CCW from A4C until RV disappears — only LV and LA visible", "Anterior wall (top) and inferior wall (bottom) in this view", "LAA best seen with slight posterior tilt"],
    pitfalls: ["Oblique cut includes RV — rotate further CCW", "Inferior wall foreshortening"],
    measurements: ["LV volume (biplane Simpson)", "LAA assessment"],
  },
  "tte:a3c": {
    description: "Also called Apical Long Axis (APLAX). Obtained by rotating ~120° CCW from A4C. Shows LV, LA, LVOT, and aortic valve. Mirrors the PLAX view from the apex.",
    structures: ["LV", "LA", "LVOT", "Aortic valve", "Mitral valve", "Aortic root"],
    howToGet: ["From A4C, rotate probe ~120° counterclockwise", "LVOT and AV come into view", "Mirrors the PLAX view from the apex"],
    tips: ["Mirrors PLAX — useful for confirming LVOT measurements", "Good for CW Doppler through AV when A5C is suboptimal", "Assess posterior and anteroseptal walls"],
    pitfalls: ["Oblique cut may include RV — rotate further", "Foreshortening of LV apex"],
    measurements: ["LVOT diameter (alternative)", "AV gradient (CW)", "LV volume (triplane)"],
  },
  "tte:subcostal": {
    description: "Obtained from below the xiphoid process with the probe flat against the abdomen. Provides a unique view of the IAS, IVC, and hepatic veins. Often the only adequate view in patients with COPD or post-surgery.",
    structures: ["RV", "LV", "RA", "LA", "IAS", "IVC", "Hepatic veins", "Liver"],
    howToGet: ["Position probe below xiphoid, probe flat", "Marker dot toward patient's left", "Angle probe toward left shoulder", "Ask patient to take a deep breath to bring heart closer"],
    tips: ["Best view for IAS assessment — ASD/PFO", "IVC assessment for RAP estimation", "Often best view in COPD/barrel chest patients"],
    pitfalls: ["Hepatic vein mistaken for IVC", "Difficult in obese patients — try lateral decubitus"],
    measurements: ["IVC diameter", "IVC collapsibility index", "RAP estimate"],
  },
  "tte:suprasternal": {
    description: "Obtained from the suprasternal notch with the patient's neck extended. Shows the aortic arch and its branches. Used for aortic coarctation assessment and diastolic flow reversal in AR.",
    structures: ["Aortic arch", "Innominate artery", "Left carotid artery", "Left subclavian artery", "Descending aorta", "RPA (cross-section)"],
    howToGet: ["Position probe in suprasternal notch", "Extend patient's neck with shoulder roll", "Marker dot toward left", "Rotate to align with aortic arch"],
    tips: ["Extend patient's neck with shoulder roll for better access", "Aortic arch visible as 'candy cane' shape", "Diastolic flow reversal in descending aorta = significant AR"],
    pitfalls: ["Difficult in short necks or COPD", "Probe pressure may cause discomfort"],
    measurements: ["Aortic arch diameter", "Descending aorta diastolic flow reversal"],
  },
  "tte:mpi_tei": {
    description: "The Myocardial Performance Index (Tei Index) is a Doppler-derived measure of global ventricular function combining systolic and diastolic time intervals. It is load-independent and applicable to both LV and RV.",
    structures: ["Mitral valve inflow (LV MPI)", "LVOT outflow (LV MPI)", "Tricuspid valve inflow (RV MPI)", "RVOT / pulmonic outflow (RV MPI)"],
    howToGet: ["Position PW sample between AV valve tips and outflow tract", "Single-beat method: place sample to capture both inflow and outflow on same cycle", "Measure ICT, IRT, and ET from Doppler trace"],
    tips: ["Single-beat method: place PW sample between AV inflow and outflow valve to capture both on one cycle", "LV MPI normal ≤0.40 (PW Doppler) | ≤0.54 (Tissue Doppler / TDI)", "RV MPI normal ≤0.40 (PW Doppler) | ≤0.54 (Tissue Doppler / TDI)", "TDI-MPI: sample at lateral mitral or tricuspid annulus — more reproducible than PW method"],
    pitfalls: ["Atrial fibrillation: MPI is unreliable due to variable RR intervals", "Elevated filling pressures shorten IRT, which can falsely normalise MPI"],
    measurements: ["ICT (ms)", "IRT (ms)", "ET (ms)", "MPI = (ICT + IRT) / ET"],
  },

  // ─── TEE ────────────────────────────────────────────────────────────────────
  "tee:me4c": {
    description: "The foundational TEE view. Provides simultaneous assessment of all four cardiac chambers, both AV valves, and the interatrial septum. Equivalent to the TTE apical 4-chamber but with superior resolution.",
    structures: ["LV (all walls, apex)", "RV", "LA", "RA", "Mitral valve (A2/P2 segments)", "Tricuspid valve", "Interatrial septum", "Moderator band (RV)"],
    howToGet: ["Advance probe to mid-esophagus (30–35 cm from incisors)", "Set multiplane angle to 0°", "Apply gentle anteflexion to bring all four chambers into view", "Optimize depth to include the apex — avoid foreshortening"],
    tips: ["The RV should appear smaller than the LV — if equal or larger, suspect RV dilation", "Tilt the probe slightly posteriorly to visualise the coronary sinus", "Advance 1–2 cm to open up the LV apex and avoid foreshortening"],
    pitfalls: ["Foreshortening of LV apex underestimates LV size and EF", "IAS dropout is common at 0° — use color Doppler to confirm ASD"],
    measurements: ["LV biplane volumes/EF", "LA area", "MV E/A/DT", "TR Vmax/RVSP"],
    criticalFindings: ["New LV wall motion abnormality (ischaemia)", "Severe MR or TR", "Large pericardial effusion"],
  },
  "tee:me2c": {
    description: "Obtained by rotating the multiplane angle from 0° to 90° without moving the probe. Provides the only TEE view of the LV anterior wall (LAD territory) and is essential for LAA assessment.",
    structures: ["LV (anterior and inferior walls)", "LA", "LAA", "Mitral valve (A1/P1 and A3/P3 segments)", "Left pulmonary veins"],
    howToGet: ["From ME 4-chamber, rotate multiplane angle to 90°", "Do not advance or withdraw the probe", "Optimize to show LV anterior and inferior walls in full length"],
    tips: ["Only TEE view of the LV anterior wall — critical for LAD ischaemia monitoring", "LAA is best seen at 90° with slight retroflexion", "Rotate slightly left/right to optimize LAA visualization"],
    pitfalls: ["Oblique cut may show RV — rotate to true 90°", "LAA thrombus can be missed without dedicated LAA views"],
    measurements: ["LV volumes (Simpson)", "LAA diameter/area", "LAA flow velocity"],
    criticalFindings: ["LAA thrombus", "Anterior wall motion abnormality"],
  },
  "tee:melax": {
    description: "Obtained at 120–135° multiplane angle. The TEE equivalent of the TTE PLAX view. Best view for LVOT, aortic valve, and mitral valve assessment in the long axis.",
    structures: ["LV (posterior and anteroseptal walls)", "LA", "LVOT", "Aortic valve", "Mitral valve (A2/P2)", "Aortic root", "Ascending aorta"],
    howToGet: ["From ME 2-chamber, continue rotating multiplane angle to 120–135°", "LVOT and AV come into view", "Optimize for LVOT diameter measurement"],
    tips: ["Best TEE view for LVOT diameter measurement (for AVA calculation)", "Assess aortic root and proximal ascending aorta", "MV posterior leaflet (P2) is closest to probe"],
    pitfalls: ["Angle variation (120° vs 135°) affects LVOT diameter — standardize", "Aortic root may be foreshortened if angle is not optimized"],
    measurements: ["LVOT diameter", "Aortic root diameter", "Sinus of Valsalva", "Sinotubular junction"],
  },
  "tee:meavsax": {
    description: "Obtained at 30–60° multiplane angle. Shows the aortic valve in cross-section. Essential for AV morphology assessment (bicuspid vs tricuspid), planimetry, and aortic root anatomy.",
    structures: ["Aortic valve (3 cusps: RCC, LCC, NCC)", "RVOT", "Pulmonary valve", "LA", "RA", "Interatrial septum", "Tricuspid valve"],
    howToGet: ["From ME 4-chamber, rotate multiplane angle to 30–60°", "AV appears in cross-section ('Mercedes-Benz')", "Optimize to show all three cusps symmetrically"],
    tips: ["'Mercedes-Benz' sign = normal tricuspid AV", "Bicuspid AV: 2 cusps with raphe — fish-mouth opening", "Best view for AV planimetry in AS"],
    pitfalls: ["Bicuspid AV may appear tricuspid if not fully open", "Oblique cut may make cusps appear unequal"],
    measurements: ["AV planimetry (AVA)", "RVOT diameter", "Pulmonary valve annulus"],
  },
  "tee:mebicaval": {
    description: "Obtained at 80–110° multiplane angle with slight rightward rotation. Shows the IAS, SVC, and IVC. Essential for ASD/PFO assessment, transseptal puncture guidance, and TAVR/TEER procedures.",
    structures: ["RA", "LA", "IAS (fossa ovalis)", "SVC", "IVC", "Right pulmonary veins", "Eustachian valve"],
    howToGet: ["From ME 4-chamber, rotate multiplane angle to 80–110°", "Turn probe rightward (clockwise) to bring SVC and IVC into view", "IAS should be perpendicular to beam for best resolution"],
    tips: ["IAS is perpendicular to ultrasound beam — best view for ASD/PFO", "Agitated saline contrast: bubbles crossing IAS = PFO/ASD", "Eustachian valve may be mistaken for IAS thrombus"],
    pitfalls: ["IAS dropout at 0° — always use bicaval view for IAS assessment", "Prominent Eustachian valve may be mistaken for RA mass"],
    measurements: ["ASD diameter", "IAS length", "SVC diameter"],
    criticalFindings: ["ASD/PFO with significant shunt", "RA mass or thrombus"],
  },
  "tee:mervio": {
    description: "Obtained at 60–90° multiplane angle with slight rightward rotation. Shows the RV inflow and outflow tracts simultaneously. Essential for RVOT assessment and pulmonary valve evaluation.",
    structures: ["RV", "RA", "Tricuspid valve", "RVOT", "Pulmonary valve", "MPA"],
    howToGet: ["From ME 4-chamber, rotate multiplane angle to 60–90°", "Turn probe slightly rightward", "RVOT and TV should be visible simultaneously"],
    tips: ["Best view for TV morphology and RVOT assessment", "Assess for RVOT obstruction in HOCM or post-repair ToF", "PW Doppler in RVOT for pulmonary stenosis gradient"],
    pitfalls: ["Oblique cut may not show true RVOT — adjust angle", "TV regurgitation jet may be eccentric — use color Doppler"],
    measurements: ["RVOT diameter", "TV annulus", "Pulmonary valve gradient"],
  },
  "tee:meaorta": {
    description: "Obtained at 0° (SAX) and 90–120° (LAX) multiplane angles in the mid-esophagus. Shows the ascending aorta. Essential for aortic dissection assessment and pre-TAVR planning.",
    structures: ["Ascending aorta", "Aortic root", "Sinotubular junction", "Pulmonary artery (adjacent)"],
    howToGet: ["Withdraw probe slightly from ME 4-chamber position", "0° for SAX view of ascending aorta", "Rotate to 90–120° for LAX view"],
    tips: ["Ascending aorta SAX: circular cross-section — measure diameter", "LAX: assess for dissection flap, intramural hematoma", "PA is adjacent to ascending aorta — do not confuse"],
    pitfalls: ["Blind spot in distal ascending aorta (interposition of right bronchus)", "Artifact from calcified aorta may mimic dissection flap"],
    measurements: ["Ascending aorta diameter (SAX and LAX)", "Sinotubular junction"],
    criticalFindings: ["Aortic dissection flap", "Intramural hematoma", "Aortic aneurysm >5 cm"],
  },
  "tee:tgsax": {
    description: "Obtained by advancing the probe into the stomach and anteflexing. Shows the LV in short axis at the mid-papillary level. Essential for intraoperative monitoring and regional wall motion assessment.",
    structures: ["LV (all 6 mid segments)", "Anterolateral papillary muscle", "Posteromedial papillary muscle", "RV (anterior)"],
    howToGet: ["Advance probe into stomach (40–45 cm)", "Anteflex to bring LV into view", "Set multiplane angle to 0°", "Optimize for circular LV cross-section"],
    tips: ["Best intraoperative view for continuous LV monitoring", "All 6 LV mid segments visible — ideal for RWMA detection", "Papillary muscles: anterolateral (LAD/LCx) vs posteromedial (RCA)"],
    pitfalls: ["Oblique cut gives oval LV — adjust anteflexion", "Near-field artifact from stomach wall"],
    measurements: ["LV EF (visual)", "Wall motion score", "LV dimensions"],
  },
  "tee:tg2c": {
    description: "Obtained at 90° multiplane angle from TG SAX position. Shows the LV anterior and inferior walls in long axis. Used for LV volume assessment and wall motion.",
    structures: ["LV (anterior and inferior walls)", "LA", "Mitral valve", "Papillary muscles"],
    howToGet: ["From TG SAX, rotate multiplane angle to 90°", "LV anterior and inferior walls visible", "Optimize depth to include apex"],
    tips: ["Anterior wall (top) = LAD territory; inferior wall (bottom) = RCA territory", "Useful for LV volume assessment when apical views are suboptimal", "Advance probe slightly to optimize apex visualization"],
    pitfalls: ["Foreshortening of LV apex is common", "Oblique cut may include RV"],
    measurements: ["LV volume (Simpson)", "Wall motion score"],
  },
  "tee:tglax": {
    description: "Obtained at 90–120° multiplane angle from TG position. Shows the LVOT, aortic valve, and LV in long axis. Best transgastric view for LVOT VTI measurement.",
    structures: ["LV", "LVOT", "Aortic valve", "Mitral valve", "LA", "Aortic root"],
    howToGet: ["From TG 2-chamber, rotate multiplane angle to 90–120°", "LVOT and AV come into view", "Align PW Doppler cursor parallel to LVOT flow"],
    tips: ["Best TG view for LVOT VTI — Doppler beam parallel to flow", "Useful when apical views are unavailable (e.g., post-sternotomy)", "CW through AV for gradient measurement"],
    pitfalls: ["Underalignment of Doppler cursor underestimates VTI", "Foreshortening of LVOT may affect diameter measurement"],
    measurements: ["LVOT VTI", "AV gradient (CW)", "LVOT diameter"],
  },
  "tee:tgrvio": {
    description: "Obtained at 0–30° multiplane angle from TG position with rightward rotation. Shows the RV inflow. Used for TV assessment and RV function evaluation.",
    structures: ["RV", "RA", "Tricuspid valve", "IVC", "Hepatic veins"],
    howToGet: ["From TG SAX, rotate probe rightward (clockwise)", "Set multiplane angle to 0–30°", "TV and RV inflow should come into view"],
    tips: ["Best TG view for TV assessment", "Assess for TV regurgitation with color Doppler", "RV inflow: assess for RA thrombus or mass"],
    pitfalls: ["Difficult to obtain in all patients", "TV may be partially obscured by near-field artifact"],
    measurements: ["TV annulus", "TR Vmax", "RV dimensions"],
  },
  "tee:ueaorticarch": {
    description: "Obtained by withdrawing the probe to the upper esophagus (20–25 cm). Shows the aortic arch in long axis. Essential for aortic arch pathology assessment.",
    structures: ["Aortic arch", "Innominate artery", "Left carotid artery", "Left subclavian artery", "Descending aorta"],
    howToGet: ["Withdraw probe to upper esophagus (20–25 cm)", "Set multiplane angle to 0°", "Rotate probe leftward to bring arch into view"],
    tips: ["Aortic arch visible as 'candy cane' — assess for dissection, atheroma", "Retrograde flow in descending aorta = significant AR", "Assess arch atheroma before cardiac surgery (embolic risk)"],
    pitfalls: ["Blind spot in distal ascending aorta", "Arch atheroma may be underestimated"],
    measurements: ["Aortic arch diameter", "Arch atheroma grade (1–5)"],
    criticalFindings: ["Type A aortic dissection extending to arch", "Severe arch atheroma (Grade 4–5)", "Aortic arch aneurysm"],
  },
  "tee:uepv": {
    description: "Obtained at 90° multiplane angle in the upper esophagus. Shows the pulmonary veins entering the LA. Used for pulmonary vein flow assessment and LAAO/TEER guidance.",
    structures: ["Left superior pulmonary vein (LSPV)", "Left inferior pulmonary vein (LIPV)", "Right superior pulmonary vein (RSPV)", "LA", "LAA"],
    howToGet: ["From UE aortic arch, rotate multiplane angle to 90°", "Rotate probe leftward for left PVs, rightward for right PVs", "PW Doppler in PV for flow assessment"],
    tips: ["PV flow: S wave (systolic), D wave (diastolic), Ar wave (atrial reversal)", "Blunted S wave or dominant D wave suggests elevated LA pressure", "LSPV ridge ('warfarin ridge') may be mistaken for LAA thrombus"],
    pitfalls: ["LSPV ridge mistaken for LAA thrombus — assess with color Doppler", "Ar wave >35 cm/s suggests elevated LVEDP"],
    measurements: ["PV S/D ratio", "PV Ar velocity/duration", "PV diameter"],
  },

  // ─── ICE ────────────────────────────────────────────────────────────────────
  "ice:home": {
    description: "The initial ICE view obtained when the catheter is in the right atrium. Shows the RA, TV, RV, and IAS. Starting point for all ICE-guided procedures.",
    structures: ["RA", "RV", "Tricuspid valve", "IAS", "Eustachian valve", "Crista terminalis"],
    howToGet: ["Advance ICE catheter to RA (via femoral vein)", "Neutral position — no flexion", "Rotate to bring TV and IAS into view"],
    tips: ["Home view is the reference position for all ICE navigation", "Identify Eustachian valve — important landmark for transseptal puncture", "Crista terminalis: posterior RA ridge — do not confuse with thrombus"],
    pitfalls: ["Eustachian valve mistaken for IAS thrombus", "Catheter artifact in RA"],
    measurements: ["RA dimensions", "IAS thickness"],
  },
  "ice:avview": {
    description: "Obtained by advancing the ICE catheter and rotating anteriorly. Shows the aortic valve in short axis. Used for TAVR sizing and LAAO guidance.",
    structures: ["Aortic valve (3 cusps)", "RVOT", "Pulmonary valve", "LA", "IAS"],
    howToGet: ["From home view, advance catheter slightly", "Rotate anteriorly (clockwise)", "AV appears in cross-section"],
    tips: ["Best ICE view for AV morphology", "Assess for bicuspid AV before TAVR", "Color Doppler for AR assessment"],
    pitfalls: ["Oblique cut may make cusps appear unequal", "Near-field artifact from catheter"],
    measurements: ["AV planimetry", "RVOT diameter"],
  },
  "ice:mvlhview": {
    description: "Obtained by advancing the ICE catheter to the right atrium and rotating posteriorly. Shows the mitral valve and left heart structures. Used for TEER and LAAO guidance.",
    structures: ["Mitral valve", "LV", "LA", "LVOT", "Aortic valve"],
    howToGet: ["From home view, rotate posteriorly (counterclockwise)", "MV and left heart come into view", "Advance slightly for better LV visualization"],
    tips: ["Best ICE view for MV assessment during TEER", "Color Doppler for MR jet assessment", "Assess MV leaflet morphology and coaptation"],
    pitfalls: ["Foreshortening of LV apex", "MV may be partially obscured by catheter"],
    measurements: ["MV annulus", "MR vena contracta", "LV EF"],
  },
  "ice:transseptal": {
    description: "ICE view used to guide transseptal puncture. Shows the IAS, fossa ovalis, and adjacent structures. Essential for safe transseptal access.",
    structures: ["IAS", "Fossa ovalis", "LA", "RA", "Aortic root (anterior)", "Pulmonary veins (posterior)"],
    howToGet: ["From home view, rotate to bring IAS perpendicular to beam", "Identify fossa ovalis — thin central portion of IAS", "Confirm needle tenting before puncture"],
    tips: ["Fossa ovalis is the thinnest part of IAS — target for transseptal puncture", "Needle tenting confirms correct position before puncture", "Aorta is anterior — avoid anterior puncture"],
    pitfalls: ["Anterior puncture risks aortic perforation", "Posterior puncture risks pericardial effusion", "Thick IAS (lipomatous hypertrophy) may require RF energy"],
    measurements: ["IAS thickness", "Fossa ovalis diameter", "Distance from aorta"],
    criticalFindings: ["Pericardial effusion after puncture", "Aortic perforation"],
  },
  "ice:laaview": {
    description: "ICE view of the left atrial appendage. Used for LAAO device sizing and deployment guidance, and to exclude LAA thrombus before cardioversion.",
    structures: ["LAA", "LA", "LSPV", "LSPV ridge", "Mitral valve"],
    howToGet: ["From transseptal position in LA", "Rotate to bring LAA into view", "Multiple angles to assess LAA morphology"],
    tips: ["Assess LAA in multiple planes — LAA morphology varies (chicken wing, cactus, windsock)", "LSPV ridge may be mistaken for thrombus — use color Doppler", "Measure LAA ostium diameter and depth for LAAO sizing"],
    pitfalls: ["LSPV ridge mistaken for LAA thrombus", "LAA trabeculations may mimic thrombus — assess with color Doppler"],
    measurements: ["LAA ostium diameter", "LAA depth", "LAA flow velocity"],
    criticalFindings: ["LAA thrombus", "LAA spontaneous echo contrast (smoke)"],
  },

  // ─── UEA (Contrast Echo) ─────────────────────────────────────────────────
  "uea:plax": {
    description: "PLAX view optimized for contrast echocardiography. Used for LV opacification, endocardial border delineation, and myocardial perfusion assessment.",
    structures: ["LV", "LA", "Aortic valve", "Mitral valve", "LVOT"],
    howToGet: ["Standard PLAX position", "Reduce gain settings for contrast imaging", "Use low mechanical index (MI <0.2) to preserve microbubbles"],
    tips: ["Reduce gain before contrast injection to avoid saturation", "Low MI imaging preserves microbubbles for longer", "Flash sequence (high MI pulse) destroys bubbles for replenishment assessment"],
    pitfalls: ["Near-field attenuation from high bubble concentration", "Gain too high causes blooming artifact"],
    measurements: ["LV dimensions", "Myocardial perfusion score"],
  },
  "uea:psax_mv": {
    description: "PSAX MV level view for contrast echocardiography. Used for myocardial perfusion assessment in the mid-ventricular segments.",
    structures: ["LV (6 mid segments)", "Mitral valve", "Papillary muscles"],
    howToGet: ["Standard PSAX MV position", "Low MI contrast imaging", "Flash and replenishment for perfusion assessment"],
    tips: ["All 6 mid-ventricular segments visible for perfusion assessment", "Compare perfusion in LAD vs RCA territories", "Perfusion defect = absent or delayed bubble replenishment"],
    pitfalls: ["Near-field attenuation", "Acoustic shadowing from high bubble concentration"],
    measurements: ["Myocardial perfusion score (0–2 per segment)", "Replenishment time constant"],
  },
  "uea:psax_pap": {
    description: "PSAX papillary muscle level view for contrast echocardiography. Used for myocardial perfusion assessment in the mid-ventricular segments.",
    structures: ["LV (6 mid segments)", "Anterolateral papillary muscle", "Posteromedial papillary muscle"],
    howToGet: ["Standard PSAX papillary muscle position", "Low MI contrast imaging"],
    tips: ["Best level for 6-segment perfusion assessment", "Anterolateral PM: LAD/LCx territory; Posteromedial PM: RCA territory"],
    pitfalls: ["Near-field attenuation", "Papillary muscle level vs MV level confusion"],
    measurements: ["Myocardial perfusion score", "Wall motion score"],
  },
  "uea:a4c": {
    description: "Apical 4-chamber view for contrast echocardiography. Used for LV opacification, EF assessment, and myocardial perfusion in the apical segments.",
    structures: ["LV (apical segments)", "RV", "LA", "RA", "Mitral valve", "Tricuspid valve"],
    howToGet: ["Standard A4C position", "Low MI contrast imaging", "Optimize for endocardial border delineation"],
    tips: ["LVO: endocardial borders clearly delineated — use for EF in poor acoustic windows", "Apical segments: LAD territory — assess for apical perfusion defects", "Apical thrombus: filling defect in LV apex"],
    pitfalls: ["Foreshortening underestimates apical perfusion defects", "Apical thrombus may be obscured by near-field artifact"],
    measurements: ["LV EF (Simpson biplane)", "Apical perfusion score", "LV volumes"],
    criticalFindings: ["Apical thrombus", "Apical perfusion defect (LAD territory)"],
  },
  "uea:a2c": {
    description: "Apical 2-chamber view for contrast echocardiography. Used for LV opacification and myocardial perfusion in the anterior and inferior walls.",
    structures: ["LV (anterior and inferior walls)", "LA", "Mitral valve"],
    howToGet: ["Standard A2C position", "Low MI contrast imaging"],
    tips: ["Anterior wall: LAD territory; inferior wall: RCA territory", "Used with A4C for biplane EF calculation with contrast"],
    pitfalls: ["Oblique cut may include RV", "Inferior wall near-field artifact"],
    measurements: ["LV volume (biplane Simpson)", "Anterior/inferior perfusion score"],
  },
  "uea:a3c": {
    description: "Apical 3-chamber (APLAX) view for contrast echocardiography. Used for LV opacification and assessment of the anteroseptal and posterior walls.",
    structures: ["LV (anteroseptal and posterior walls)", "LA", "LVOT", "Aortic valve"],
    howToGet: ["Standard A3C position", "Low MI contrast imaging"],
    tips: ["Anteroseptal wall: LAD territory; posterior wall: LCx territory", "Used with A4C and A2C for triplane EF calculation"],
    pitfalls: ["Foreshortening of LV apex", "LVOT may be obscured by contrast"],
    measurements: ["LV volume (triplane)", "Anteroseptal/posterior perfusion score"],
  },

  // ─── HOCM ────────────────────────────────────────────────────────────────
  "hocm:plax": {
    description: "PLAX view in HOCM assessment. Key view for measuring IVS thickness, LVOT obstruction, and systolic anterior motion (SAM) of the mitral valve.",
    structures: ["IVS (hypertrophied)", "LV posterior wall", "LVOT", "Mitral valve (SAM)", "Aortic valve (early closure)"],
    howToGet: ["Standard PLAX position", "Optimize for IVS and LVOT visualization", "M-mode through MV for SAM assessment"],
    tips: ["SAM of MV: anterior leaflet moves toward IVS in systole — classic HOCM sign", "Aortic valve early closure: mid-systolic notch on M-mode", "Measure IVS at end-diastole — maximum hypertrophy location"],
    pitfalls: ["Oblique cut overestimates IVS thickness", "SAM may be absent at rest — provoke with Valsalva or amyl nitrite"],
    measurements: ["IVS thickness (d)", "LVOT diameter", "LVOT gradient (CW Doppler)", "SAM severity"],
    criticalFindings: ["Severe LVOT obstruction (gradient >50 mmHg)", "SAM with significant MR", "Extreme hypertrophy (IVS >30 mm)"],
  },
  "hocm:psax-mv": {
    description: "PSAX MV level view in HOCM. Used to assess MV morphology, SAM mechanism, and regional hypertrophy pattern.",
    structures: ["Mitral valve", "LV (circular)", "Hypertrophied IVS", "Papillary muscles"],
    howToGet: ["Standard PSAX MV position", "Assess MV morphology and opening pattern"],
    tips: ["Assess MV leaflet morphology — elongated anterior leaflet predisposes to SAM", "Regional hypertrophy: septal vs concentric vs apical pattern", "Papillary muscle hypertrophy and displacement contribute to SAM"],
    pitfalls: ["Oblique cut overestimates septal thickness", "Papillary muscle hypertrophy may be mistaken for mass"],
    measurements: ["IVS thickness", "LV dimensions", "MV leaflet length"],
  },
  "hocm:a4c": {
    description: "Apical 4-chamber view in HOCM. Used for chamber size assessment, MR evaluation, and apical hypertrophy detection.",
    structures: ["LV (hypertrophied)", "RV", "LA (dilated if MR present)", "RA", "Mitral valve", "Tricuspid valve"],
    howToGet: ["Standard A4C position", "Assess for apical hypertrophy (apical variant HOCM)", "Color Doppler for MR assessment"],
    tips: ["Apical variant HOCM: hypertrophy confined to apex — 'ace of spades' appearance", "MR in HOCM: typically posteriorly directed due to SAM", "LA dilation indicates significant MR or diastolic dysfunction"],
    pitfalls: ["Apical hypertrophy may be missed without contrast", "MR jet direction may be confused with LVOT flow"],
    measurements: ["LV EF", "LA volume", "MR vena contracta", "Apical wall thickness"],
    criticalFindings: ["Severe MR", "Apical aneurysm (apical variant HOCM)"],
  },
  "hocm:a5c": {
    description: "Apical 5-chamber view in HOCM. The primary view for LVOT gradient measurement with CW Doppler. Essential for HOCM severity assessment.",
    structures: ["LV", "LVOT", "Aortic valve", "Mitral valve (SAM)"],
    howToGet: ["From A4C, tilt probe anteriorly to bring LVOT into view", "Align CW Doppler cursor parallel to LVOT flow", "Measure peak and mean LVOT gradient"],
    tips: ["CW Doppler: 'dagger-shaped' late-peaking signal = HOCM (vs AS: early-peaking)", "Measure gradient at rest AND with Valsalva/exercise provocation", "LVOT gradient >50 mmHg at rest = significant obstruction"],
    pitfalls: ["Underalignment of CW cursor underestimates gradient", "'Dagger' shape may be confused with MR — use color Doppler to confirm LVOT flow"],
    measurements: ["LVOT peak gradient (CW)", "LVOT mean gradient", "Provoked gradient (Valsalva)"],
    criticalFindings: ["Resting LVOT gradient >50 mmHg", "Provoked gradient >50 mmHg"],
  },
  "hocm:a3c": {
    description: "Apical 3-chamber (APLAX) view in HOCM. Used for LVOT assessment and confirmation of SAM mechanism.",
    structures: ["LV (anteroseptal and posterior walls)", "LVOT", "Aortic valve", "Mitral valve (SAM)"],
    howToGet: ["Standard A3C position", "Assess LVOT and SAM in long axis"],
    tips: ["SAM clearly visible in this view — anterior MV leaflet moves toward IVS", "LVOT narrowing due to SAM and hypertrophied IVS", "Assess for MV leaflet elongation"],
    pitfalls: ["Foreshortening of LVOT", "SAM may be intermittent"],
    measurements: ["LVOT diameter", "SAM severity", "MV leaflet length"],
  },

  // ─── Stress Echo ─────────────────────────────────────────────────────────
  "stress:rest-plax": {
    description: "Resting PLAX view acquired before stress echo. Baseline for comparison with stress images. Assess LV function, wall motion, and valve morphology at rest.",
    structures: ["LV", "LA", "Aortic valve", "Mitral valve", "LVOT"],
    howToGet: ["Standard PLAX position", "Acquire at end-expiration", "Optimize for wall motion assessment"],
    tips: ["Acquire all rest views before starting stress protocol", "Optimize image quality at rest — harder to obtain during stress", "Document any baseline wall motion abnormalities"],
    pitfalls: ["Poor image quality at rest predicts poor stress images", "Baseline RWMA may be missed if gain is not optimized"],
    measurements: ["LV dimensions", "EF (visual)", "Baseline wall motion score"],
  },
  "stress:rest-psax-mv": {
    description: "Resting PSAX MV level view for stress echo. Baseline for 6-segment wall motion assessment.",
    structures: ["LV (6 mid segments)", "Mitral valve", "Papillary muscles"],
    howToGet: ["Standard PSAX MV position", "Acquire at end-expiration"],
    tips: ["6 segments visible — best view for regional ischaemia detection", "Compare with stress images side-by-side"],
    pitfalls: ["Oblique cut may miss regional RWMA"],
    measurements: ["Wall motion score (6 segments)"],
  },
  "stress:rest-psax-pm": {
    description: "Resting PSAX papillary muscle level view for stress echo. Baseline for mid-ventricular wall motion assessment.",
    structures: ["LV (6 mid segments)", "Anterolateral PM", "Posteromedial PM"],
    howToGet: ["Standard PSAX PM position", "Acquire at end-expiration"],
    tips: ["PM level: best for RCA territory (inferior, inferolateral)"],
    pitfalls: ["PM level vs MV level confusion"],
    measurements: ["Wall motion score (6 segments)"],
  },
  "stress:rest-a4c": {
    description: "Resting A4C view for stress echo. Baseline for apical and mid-ventricular wall motion assessment.",
    structures: ["LV (apical segments)", "RV", "LA", "RA", "Mitral valve"],
    howToGet: ["Standard A4C position", "Acquire at end-expiration"],
    tips: ["Apical segments: LAD territory", "Assess for resting apical RWMA or LV dilation"],
    pitfalls: ["Foreshortening underestimates apical segments"],
    measurements: ["LV EF (visual)", "Wall motion score (apical segments)"],
  },
  "stress:rest-a2c": {
    description: "Resting A2C view for stress echo. Baseline for anterior and inferior wall assessment.",
    structures: ["LV (anterior and inferior walls)", "LA", "Mitral valve"],
    howToGet: ["Standard A2C position", "Acquire at end-expiration"],
    tips: ["Anterior wall: LAD territory; inferior wall: RCA territory"],
    pitfalls: ["Oblique cut may include RV"],
    measurements: ["Wall motion score (anterior/inferior)"],
  },
  "stress:rest-a3c": {
    description: "Resting A3C (APLAX) view for stress echo. Baseline for anteroseptal and posterior wall assessment.",
    structures: ["LV (anteroseptal and posterior walls)", "LA", "LVOT", "Aortic valve"],
    howToGet: ["Standard A3C position", "Acquire at end-expiration"],
    tips: ["Anteroseptal: LAD territory; posterior: LCx territory"],
    pitfalls: ["Foreshortening of LV apex"],
    measurements: ["Wall motion score (anteroseptal/posterior)"],
  },

  // ─── Structural Heart ─────────────────────────────────────────────────────
  "structural:tavr-sizing": {
    description: "TEE views used for TAVR annulus sizing. Multi-plane assessment of the aortic annulus, LVOT, and coronary ostia heights. Critical for device selection.",
    structures: ["Aortic annulus", "LVOT", "Sinus of Valsalva", "Sinotubular junction", "Coronary ostia (LCA, RCA)", "Aortic cusps"],
    howToGet: ["ME LAX (120–135°) for annulus diameter", "ME AV SAX (30–60°) for annulus area and perimeter", "Assess coronary ostia heights in ME LAX"],
    tips: ["Annulus is D-shaped — measure in multiple planes", "CT is gold standard for sizing — TEE confirms and guides deployment", "Coronary ostia height <10 mm increases risk of coronary obstruction"],
    pitfalls: ["Oblique cut overestimates annulus size", "Calcification may obscure annulus landmarks"],
    measurements: ["Annulus diameter (LAX and SAX)", "Annulus area and perimeter (3D)", "Coronary ostia heights", "Sinus of Valsalva diameter", "Sinotubular junction diameter"],
    criticalFindings: ["Coronary ostia height <10 mm (obstruction risk)", "Severe annular calcification", "Bicuspid AV (increased risk of paravalvular leak)"],
  },
  "structural:tavr-deployment": {
    description: "Real-time TEE guidance during TAVR deployment. Monitors valve position, expansion, and immediate post-deployment assessment.",
    structures: ["Aortic valve prosthesis", "LVOT", "Aortic root", "Coronary ostia", "Mitral valve (SAM risk)"],
    howToGet: ["ME LAX (120–135°) for deployment guidance", "ME AV SAX for valve expansion assessment", "A5C equivalent for LVOT gradient post-deployment"],
    tips: ["Valve depth: 3–6 mm below annulus is optimal", "Assess for paravalvular leak immediately after deployment", "Check coronary flow after deployment — color Doppler"],
    pitfalls: ["Valve embolization: device moves toward ascending aorta — emergency", "Annular rupture: pericardial effusion, hemodynamic collapse"],
    measurements: ["Valve depth (mm below annulus)", "Paravalvular leak grade", "LVOT gradient post-deployment", "Coronary flow velocity"],
    criticalFindings: ["Paravalvular leak ≥ moderate", "Coronary obstruction", "Valve embolization", "Annular rupture with pericardial effusion"],
  },
  "structural:teer-iasn": {
    description: "TEE guidance for transseptal puncture during TEER (MitraClip/PASCAL). Bicaval and short-axis views to guide needle position and confirm LA access.",
    structures: ["IAS", "Fossa ovalis", "LA", "RA", "Aortic root (anterior)", "MV (posterior)"],
    howToGet: ["ME Bicaval (90–110°) for anterior-posterior needle position", "ME AV SAX (30–60°) for superior-inferior needle position", "Confirm tenting and puncture with color Doppler"],
    tips: ["Posterior and superior puncture is ideal for TEER — allows clip delivery to MV", "Tenting confirms correct needle position before puncture", "Target height: 3.5–4.5 cm above MV annulus"],
    pitfalls: ["Anterior puncture risks aortic perforation", "Too inferior puncture limits maneuverability of clip delivery system"],
    measurements: ["Puncture height above MV annulus", "IAS thickness", "Distance from aorta"],
    criticalFindings: ["Pericardial effusion after puncture", "Aortic perforation"],
  },
  "structural:teer-guidance": {
    description: "Real-time TEE guidance during TEER clip delivery and deployment. Multi-plane assessment of clip position, leaflet grasping, and MR reduction.",
    structures: ["Mitral valve (A2/P2 segments)", "LV", "LA", "Clip delivery system", "MR jet"],
    howToGet: ["ME 4-chamber (0°) for clip alignment", "ME Commissural (60°) for A2/P2 assessment", "ME LAX (120–135°) for clip depth", "3D TEE for en face MV view"],
    tips: ["Clip should be perpendicular to MV coaptation line", "Assess leaflet insertion — both leaflets should be grasped", "MR should reduce by ≥50% after clip deployment"],
    pitfalls: ["Single leaflet attachment: clip grasps only one leaflet — reposition", "Clip too anterior or posterior — use commissural view to confirm A2/P2"],
    measurements: ["MR vena contracta pre/post", "MV gradient post-clip", "MV area post-clip", "Residual MR grade"],
    criticalFindings: ["Single leaflet attachment", "Severe residual MR", "MV stenosis post-clip (MVA <1.5 cm²)"],
  },
  "structural:laao-sizing": {
    description: "TEE guidance for LAAO device sizing and deployment (Watchman/Amulet). Multi-plane assessment of LAA ostium, depth, and morphology.",
    structures: ["LAA", "LA", "LSPV", "LSPV ridge", "Mitral valve", "Left circumflex artery (adjacent)"],
    howToGet: ["ME 0°, 45°, 90°, 135° for LAA assessment", "Measure LAA ostium diameter and depth in multiple planes", "3D TEE for comprehensive LAA morphology"],
    tips: ["Measure LAA ostium at 4 angles — use maximum diameter for device sizing", "LAA depth must exceed device diameter for adequate seal", "Assess LSPV ridge — may affect device positioning"],
    pitfalls: ["LSPV ridge mistaken for LAA thrombus — use color Doppler", "LAA thrombus: contraindication to LAAO — exclude with TEE before procedure"],
    measurements: ["LAA ostium diameter (4 angles)", "LAA depth", "LSPV ridge width", "LAA flow velocity"],
    criticalFindings: ["LAA thrombus (contraindication)", "Inadequate LAA depth for device", "Pericardial effusion after access"],
  },

  // ─── POCUS EFAST ────────────────────────────────────────────────────────
  "pocus_efast:ruq": {
    description: "Right upper quadrant (Morison's pouch) view for EFAST. Assesses for free fluid between the liver and right kidney. The most sensitive EFAST view for hemoperitoneum.",
    structures: ["Liver", "Right kidney", "Morison's pouch (hepatorenal space)", "Diaphragm", "Right pleural space"],
    howToGet: ["Position probe in right mid-axillary line, 8th–11th ICS", "Marker dot toward head", "Fan through liver-kidney interface"],
    tips: ["Morison's pouch: most dependent space in right upper quadrant — fluid collects here first", "Assess diaphragm for hemothorax (fluid above diaphragm)", "Anechoic stripe between liver and kidney = free fluid"],
    pitfalls: ["Fat between liver and kidney may mimic fluid — look for sharp borders", "Perinephric fat is echogenic — true fluid is anechoic"],
    measurements: ["Free fluid depth (cm)", "Hemothorax depth"],
    criticalFindings: ["Free fluid in Morison's pouch (hemoperitoneum)", "Hemothorax"],
  },
  "pocus_efast:luq": {
    description: "Left upper quadrant (splenorenal space) view for EFAST. Assesses for free fluid between the spleen and left kidney. More difficult to obtain than RUQ due to rib interference.",
    structures: ["Spleen", "Left kidney", "Splenorenal space", "Diaphragm", "Left pleural space"],
    howToGet: ["Position probe in left posterior axillary line, 8th–11th ICS", "Marker dot toward head", "Fan through spleen-kidney interface"],
    tips: ["More posterior and superior than RUQ — probe needs to be more posterior", "Spleen is smaller than liver — may need to fan widely", "Assess diaphragm for left hemothorax"],
    pitfalls: ["Rib shadowing is common — slide probe between ribs", "Spleen may be small and difficult to identify"],
    measurements: ["Free fluid depth (cm)", "Hemothorax depth"],
    criticalFindings: ["Free fluid in splenorenal space", "Left hemothorax"],
  },
  "pocus_efast:pelvis": {
    description: "Pelvic view for EFAST. Assesses for free fluid in the pouch of Douglas (females) or rectovesical pouch (males). Most dependent space in the supine patient.",
    structures: ["Bladder", "Uterus (females)", "Pouch of Douglas (females)", "Rectovesical pouch (males)", "Bowel"],
    howToGet: ["Position probe just superior to pubic symphysis", "Marker dot toward patient's right (transverse) or head (sagittal)", "Fan through bladder to assess posterior spaces"],
    tips: ["Full bladder acts as acoustic window — assess before catheterization", "Pouch of Douglas: most dependent space in females — fluid collects here", "Transverse and sagittal views for complete assessment"],
    pitfalls: ["Empty bladder limits visualization", "Bowel gas may obscure posterior spaces"],
    measurements: ["Free fluid depth (cm)"],
    criticalFindings: ["Free fluid in pouch of Douglas or rectovesical pouch"],
  },
  "pocus_efast:subxiphoid": {
    description: "Subxiphoid cardiac view for EFAST. Assesses for pericardial effusion and cardiac tamponade. Also provides a quick assessment of cardiac function.",
    structures: ["Heart (all 4 chambers)", "Pericardium", "Liver (acoustic window)", "IVC"],
    howToGet: ["Position probe just below xiphoid, probe flat against abdomen", "Marker dot toward patient's left", "Angle probe toward left shoulder", "Use liver as acoustic window"],
    tips: ["Pericardial effusion: anechoic stripe surrounding heart", "Tamponade: RV collapse in diastole, IVC plethora", "Cardiac activity confirms PEA vs asystole in arrest"],
    pitfalls: ["Pericardial fat may mimic effusion — fat is anterior and echogenic", "Difficult in obese patients or post-abdominal surgery"],
    measurements: ["Pericardial effusion size (cm)", "RV collapse timing"],
    criticalFindings: ["Pericardial effusion with RV collapse (tamponade)", "Cardiac standstill (asystole)"],
  },
  "pocus_efast:rthorax": {
    description: "Right thoracic view for EFAST. Assesses for right pneumothorax (lung sliding) and hemothorax.",
    structures: ["Pleural line", "Ribs", "Lung (A-lines/B-lines)", "Diaphragm"],
    howToGet: ["Position probe in 2nd–3rd ICS, midclavicular line", "Marker dot toward head", "Identify pleural line between two ribs ('bat sign')"],
    tips: ["Lung sliding = normal (rules out pneumothorax at that point)", "Absent lung sliding + A-lines = pneumothorax", "M-mode: 'seashore sign' = normal; 'barcode sign' = pneumothorax"],
    pitfalls: ["Absent lung sliding can also be seen in mainstem intubation, pleurodesis", "Lung point: transition from absent to present sliding = confirms pneumothorax"],
    measurements: ["Lung sliding: present/absent"],
    criticalFindings: ["Absent lung sliding (pneumothorax)", "Hemothorax"],
  },
  "pocus_efast:lthorax": {
    description: "Left thoracic view for EFAST. Assesses for left pneumothorax (lung sliding) and hemothorax.",
    structures: ["Pleural line", "Ribs", "Lung (A-lines/B-lines)", "Diaphragm"],
    howToGet: ["Position probe in 2nd–3rd ICS, left midclavicular line", "Marker dot toward head", "Identify pleural line between two ribs"],
    tips: ["Same technique as right thorax", "Lung sliding rules out pneumothorax at that point", "M-mode: 'seashore sign' = normal; 'barcode sign' = pneumothorax"],
    pitfalls: ["Cardiac motion may cause false-positive lung sliding near apex"],
    measurements: ["Lung sliding: present/absent"],
    criticalFindings: ["Absent lung sliding (pneumothorax)", "Hemothorax"],
  },

  // ─── POCUS Cardiac ───────────────────────────────────────────────────────
  "pocus_cardiac:plax": {
    description: "PLAX view for cardiac POCUS. Quick assessment of LV function, pericardial effusion, and valve morphology.",
    structures: ["LV", "LA", "Aortic valve", "Mitral valve", "Pericardium"],
    howToGet: ["Standard PLAX position", "Optimize for LV wall motion and pericardium"],
    tips: ["Hyperdynamic LV (EF >70%): small cavity, vigorous walls — consider sepsis, hypovolemia", "Severely reduced LV (EF <30%): large, poorly contracting — consider cardiogenic shock", "Pericardial effusion: anechoic stripe posterior to LV"],
    pitfalls: ["Pericardial fat (anterior) vs effusion (posterior) — fat is echogenic", "Foreshortening underestimates LV size"],
    measurements: ["LV EF (visual)", "Pericardial effusion size"],
    criticalFindings: ["Severely reduced LV function", "Large pericardial effusion", "Cardiac tamponade"],
  },
  "pocus_cardiac:psax_mv": {
    description: "PSAX MV level view for cardiac POCUS. Quick assessment of LV function and regional wall motion.",
    structures: ["LV (6 mid segments)", "Mitral valve", "Papillary muscles"],
    howToGet: ["Standard PSAX MV position"],
    tips: ["Circular LV: equal wall thickening in systole = normal", "D-sign (flattened IVS): RV pressure/volume overload", "Regional RWMA: one or more segments not thickening"],
    pitfalls: ["D-sign may be subtle — compare IVS shape in systole vs diastole"],
    measurements: ["LV EF (visual)", "IVS shape (D-sign)"],
    criticalFindings: ["D-sign (RV overload)", "Regional RWMA (ACS)", "Severely reduced LV function"],
  },
  "pocus_cardiac:psax_pm": {
    description: "PSAX papillary muscle level view for cardiac POCUS. Assessment of LV function and RV size.",
    structures: ["LV (6 mid segments)", "RV", "Papillary muscles"],
    howToGet: ["Standard PSAX PM position"],
    tips: ["RV:LV ratio >1 at PM level: severe RV dilation — consider PE", "D-sign at PM level: RV pressure overload"],
    pitfalls: ["RV may be difficult to visualize at PM level"],
    measurements: ["RV:LV ratio", "LV EF (visual)"],
    criticalFindings: ["RV:LV ratio >1 (massive PE)", "D-sign"],
  },
  "pocus_cardiac:a4c": {
    description: "A4C view for cardiac POCUS. Comprehensive assessment of all four chambers, biventricular function, and pericardial effusion.",
    structures: ["LV", "RV", "LA", "RA", "Mitral valve", "Tricuspid valve", "Pericardium"],
    howToGet: ["Standard A4C position"],
    tips: ["RV:LV ratio >0.6: RV dilation — consider PE, RV infarct, cor pulmonale", "McConnell's sign: RV free wall akinesis with apical sparing — highly specific for PE", "Pericardial effusion: circumferential anechoic stripe"],
    pitfalls: ["Foreshortening underestimates RV size", "Pericardial fat vs effusion"],
    measurements: ["RV:LV ratio", "LV EF (visual)", "Pericardial effusion size"],
    criticalFindings: ["McConnell's sign (PE)", "RV:LV ratio >1", "Cardiac tamponade"],
  },
  "pocus_cardiac:subcostal": {
    description: "Subcostal view for cardiac POCUS. Assessment of pericardial effusion, IVC, and cardiac function when other windows are unavailable.",
    structures: ["Heart (all chambers)", "Pericardium", "IVC", "Hepatic veins", "Liver"],
    howToGet: ["Standard subcostal position", "Assess IVC in long axis by rotating probe 90°"],
    tips: ["Best view for pericardial effusion assessment", "IVC >2.1 cm + <50% collapse = elevated RAP", "IVC <1.7 cm + >50% collapse = low RAP (hypovolemia)"],
    pitfalls: ["Pericardial fat vs effusion", "Difficult in obese patients"],
    measurements: ["Pericardial effusion size", "IVC diameter", "IVC collapsibility"],
    criticalFindings: ["Cardiac tamponade (RV collapse)", "Plethoric IVC (RV failure, PE)"],
  },
  "pocus_cardiac:ivc": {
    description: "IVC view for cardiac POCUS. Assessment of IVC diameter and collapsibility for RAP estimation and fluid responsiveness.",
    structures: ["IVC", "Hepatic veins", "RA", "Liver"],
    howToGet: ["From subcostal position, rotate probe 90° to bring IVC in long axis", "Measure IVC 2 cm from RA-IVC junction", "Assess collapsibility with sniff or spontaneous respiration"],
    tips: ["IVC >2.1 cm + <50% collapse = RAP 10–20 mmHg", "IVC <1.7 cm + >50% collapse = RAP <5 mmHg", "Ventilated patients: IVC distensibility index for fluid responsiveness"],
    pitfalls: ["Hepatic vein mistaken for IVC", "Ventilated patients: IVC behavior is opposite to spontaneous breathing"],
    measurements: ["IVC max diameter (cm)", "IVC min diameter (cm)", "IVC collapsibility index (%)"],
    criticalFindings: ["Plethoric IVC (>2.1 cm, non-collapsing): RV failure, PE, tamponade", "Flat IVC (<1 cm): severe hypovolemia"],
  },

  // ─── POCUS Lung ──────────────────────────────────────────────────────────
  "pocus_lung:anterior_ptx": {
    description: "Anterior lung POCUS for pneumothorax assessment. Lung sliding and A-lines assessment in the most anterior lung zones.",
    structures: ["Pleural line", "Ribs", "A-lines", "Lung sliding"],
    howToGet: ["Position probe in 2nd–3rd ICS, midclavicular line", "Identify bat sign (two ribs + pleural line)", "Assess for lung sliding in real-time"],
    tips: ["Lung sliding = visceral and parietal pleura moving together = no pneumothorax", "Absent lung sliding + A-lines = pneumothorax (at that point)", "Lung point: transition from absent to present sliding = 100% specific for pneumothorax"],
    pitfalls: ["Absent lung sliding also seen in: mainstem intubation, pleurodesis, severe consolidation", "Cardiac motion near apex may cause false-positive sliding"],
    measurements: ["Lung sliding: present/absent", "Lung point: present/absent"],
    criticalFindings: ["Absent lung sliding with A-lines (pneumothorax)", "Lung point (confirms pneumothorax)"],
  },
  "pocus_lung:anterior_blines": {
    description: "Anterior lung POCUS for B-line assessment. B-lines indicate interstitial fluid (pulmonary edema, ILD). Bilateral anterior B-lines suggest cardiogenic pulmonary edema.",
    structures: ["Pleural line", "B-lines (comet tails)", "Lung parenchyma"],
    howToGet: ["Position probe in anterior chest, 2nd–5th ICS", "Assess multiple zones bilaterally", "Count B-lines per intercostal space"],
    tips: ["B-lines: vertical, hyperechoic, arise from pleural line, extend to bottom of screen, erase A-lines", "≥3 B-lines per zone = significant interstitial syndrome", "Bilateral anterior B-lines: cardiogenic pulmonary edema (sensitivity >90%)"],
    pitfalls: ["1–2 B-lines per zone can be normal (especially at bases)", "Unilateral B-lines suggest pneumonia, not pulmonary edema"],
    measurements: ["B-line count per zone", "B-line distribution (bilateral/unilateral)"],
    criticalFindings: ["Diffuse bilateral B-lines (pulmonary edema)", "Unilateral B-lines with consolidation (pneumonia)"],
  },
  "pocus_lung:plaps_right": {
    description: "Right PLAPS (posterolateral alveolar and/or pleural syndrome) zone. Assessment for pleural effusion and consolidation at the right lung base.",
    structures: ["Right lung base", "Diaphragm", "Liver", "Right pleural space", "Consolidation (if present)"],
    howToGet: ["Position probe in right posterior axillary line, below the diaphragm level", "Fan superiorly to assess lung base", "Identify diaphragm and assess for fluid above it"],
    tips: ["Pleural effusion: anechoic space above diaphragm", "Consolidation: tissue-like echogenicity with air bronchograms", "Spine sign: vertebrae visible through effusion = pleural fluid (not ascites)"],
    pitfalls: ["Ascites vs pleural effusion: spine sign differentiates", "Consolidation may be mistaken for liver"],
    measurements: ["Pleural effusion depth (cm)", "Consolidation size"],
    criticalFindings: ["Large pleural effusion", "Consolidation with air bronchograms (pneumonia)"],
  },
  "pocus_lung:plaps_left": {
    description: "Left PLAPS zone. Assessment for pleural effusion and consolidation at the left lung base.",
    structures: ["Left lung base", "Diaphragm", "Spleen", "Left pleural space", "Consolidation (if present)"],
    howToGet: ["Position probe in left posterior axillary line", "Fan superiorly to assess lung base", "Identify diaphragm and assess for fluid above it"],
    tips: ["Same technique as right PLAPS", "Spleen is smaller than liver — may need to fan more superiorly", "Left pleural effusion: anechoic space above diaphragm, lateral to spleen"],
    pitfalls: ["Spleen may be small and difficult to identify", "Gastric contents may mimic effusion"],
    measurements: ["Pleural effusion depth (cm)", "Consolidation size"],
    criticalFindings: ["Large left pleural effusion", "Left lower lobe consolidation"],
  },
  "pocus_lung:diaphragm": {
    description: "Diaphragm POCUS for assessment of diaphragm function and excursion. Used in ICU for weaning assessment and phrenic nerve palsy.",
    structures: ["Diaphragm", "Liver (right)", "Spleen (left)", "Pleural space", "Peritoneal space"],
    howToGet: ["Position probe in subcostal or lower intercostal space", "M-mode through diaphragm for excursion measurement", "Assess bilateral diaphragm movement"],
    tips: ["Normal diaphragm excursion: >1.8 cm (quiet breathing), >7 cm (deep breathing)", "Paradoxical motion (upward with inspiration) = diaphragm paralysis", "Thickening fraction >20% during inspiration = adequate diaphragm function"],
    pitfalls: ["Rib shadowing may obscure diaphragm", "Patient cooperation required for accurate measurement"],
    measurements: ["Diaphragm excursion (M-mode, cm)", "Diaphragm thickening fraction (%)"],
    criticalFindings: ["Paradoxical diaphragm motion (paralysis)", "Absent diaphragm excursion"],
  },

  // ─── POCUS RUSH ──────────────────────────────────────────────────────────
  "pocus_rush:pump_subcostal": {
    description: "RUSH protocol — Pump assessment: Subcostal view. Evaluates cardiac function and pericardial effusion in the shocked patient.",
    structures: ["Heart (all chambers)", "Pericardium", "IVC"],
    howToGet: ["Standard subcostal position", "Assess cardiac function and pericardial effusion"],
    tips: ["Hyperdynamic: septic/distributive shock", "Severely reduced: cardiogenic shock", "Pericardial effusion with tamponade physiology: obstructive shock"],
    pitfalls: ["Difficult in obese patients — use A4C or PLAX as alternative"],
    measurements: ["LV EF (visual)", "Pericardial effusion size", "IVC diameter"],
    criticalFindings: ["Cardiac tamponade", "Severely reduced LV function (cardiogenic shock)"],
  },
  "pocus_rush:pump_plax": {
    description: "RUSH protocol — Pump assessment: PLAX view. Evaluates LV function and pericardial effusion.",
    structures: ["LV", "LA", "Aortic valve", "Mitral valve", "Pericardium"],
    howToGet: ["Standard PLAX position"],
    tips: ["Hyperdynamic LV: small cavity, vigorous walls — distributive shock", "Severely reduced LV: large, poorly contracting — cardiogenic shock"],
    pitfalls: ["Foreshortening underestimates LV size"],
    measurements: ["LV EF (visual)", "Pericardial effusion size"],
    criticalFindings: ["Severely reduced LV function", "Large pericardial effusion"],
  },
  "pocus_rush:tank_ivc": {
    description: "RUSH protocol — Tank assessment: IVC view. Evaluates volume status and fluid responsiveness.",
    structures: ["IVC", "Hepatic veins", "RA"],
    howToGet: ["From subcostal position, rotate probe 90° for IVC long axis", "Measure IVC 2 cm from RA junction", "Assess collapsibility"],
    tips: ["Flat IVC (<1 cm, >50% collapse): hypovolemia — fill the tank", "Plethoric IVC (>2.1 cm, <50% collapse): RV failure, PE, tamponade — do not fill"],
    pitfalls: ["Hepatic vein mistaken for IVC", "Ventilated patients: IVC behavior is opposite"],
    measurements: ["IVC diameter (max/min)", "IVC collapsibility index"],
    criticalFindings: ["Plethoric IVC (obstructive/cardiogenic shock)", "Flat IVC (hypovolemic shock)"],
  },
  "pocus_rush:tank_ruq": {
    description: "RUSH protocol — Tank assessment: RUQ view. Assesses for free fluid (hemoperitoneum) in the shocked trauma patient.",
    structures: ["Liver", "Right kidney", "Morison's pouch", "Diaphragm"],
    howToGet: ["Standard RUQ EFAST position"],
    tips: ["Free fluid in Morison's pouch = hemoperitoneum — surgical emergency", "Assess diaphragm for hemothorax"],
    pitfalls: ["Fat between liver and kidney may mimic fluid"],
    measurements: ["Free fluid depth (cm)"],
    criticalFindings: ["Free fluid (hemoperitoneum)", "Hemothorax"],
  },
  "pocus_rush:pipes_aorta": {
    description: "RUSH protocol — Pipes assessment: Abdominal aorta. Assesses for aortic aneurysm as a cause of shock.",
    structures: ["Abdominal aorta", "Iliac arteries", "IVC", "Vertebral body"],
    howToGet: ["Position probe in epigastrium, marker dot toward head", "Fan through aorta from diaphragm to bifurcation", "Measure aorta in transverse and longitudinal planes"],
    tips: ["Normal aorta <3 cm — measure outer wall to outer wall", "AAA ≥3 cm: aneurysm; ≥5.5 cm: surgical threshold", "Periaortic hematoma: retroperitoneal fluid around aorta — ruptured AAA"],
    pitfalls: ["IVC may be mistaken for aorta — aorta is pulsatile, left of midline", "Bowel gas may obscure aorta — apply gentle pressure"],
    measurements: ["Aortic diameter (cm, outer wall to outer wall)", "Bifurcation level"],
    criticalFindings: ["AAA ≥5.5 cm", "Periaortic hematoma (ruptured AAA)", "Aortic dissection flap"],
  },
};

/**
 * Look up static content for a given module and viewId.
 * Returns undefined if no static content is available.
 */
export function getStaticViewContent(
  module: string,
  viewId: string
): StaticViewContent | undefined {
  return STATIC_CONTENT[`${module}:${viewId}`];
}

/**
 * Check if static content exists for a given module and viewId.
 */
export function hasStaticContent(module: string, viewId: string): boolean {
  return `${module}:${viewId}` in STATIC_CONTENT;
}
