CREATE TABLE `echoCorrelations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(255) NOT NULL,
	`organization` varchar(255),
	`dateReviewCompleted` varchar(20),
	`examIdentifier` varchar(50),
	`dob` varchar(20),
	`examType` varchar(100),
	`correlation1Type` varchar(100),
	`correlation1TypeOther` varchar(100),
	`correlation2Type` varchar(100),
	`correlation2TypeOther` varchar(100),
	`originalExamDos` varchar(20),
	`correlation1Dos` varchar(20),
	`correlation2Dos` varchar(20),
	`originalFindings` text,
	`corr1Findings` text,
	`corr2Findings` text,
	`concordance1` text,
	`concordance2` text,
	`overallConcordanceRate` int,
	`varianceNotes` text,
	`reviewerName` varchar(200),
	`reviewerEmail` varchar(200),
	`labId` int,
	`revieweeId` varchar(255),
	`revieweeName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `echoCorrelations_id` PRIMARY KEY(`id`)
);
