CREATE TABLE `scanCoachOverrides` (
	`id` int AUTO_INCREMENT NOT NULL,
	`module` varchar(32) NOT NULL,
	`viewId` varchar(64) NOT NULL,
	`viewName` varchar(128),
	`echoImageUrl` text,
	`anatomyImageUrl` text,
	`transducerImageUrl` text,
	`description` text,
	`howToGet` text,
	`tips` text,
	`pitfalls` text,
	`structures` text,
	`measurements` text,
	`criticalFindings` text,
	`updatedByUserId` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scanCoachOverrides_id` PRIMARY KEY(`id`)
);
