CREATE TABLE `physicianComparisonReviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`labId` int NOT NULL,
	`createdByUserId` int NOT NULL,
	`invitationId` int,
	`overReadSubmissionId` int,
	`overReadingPhysician` varchar(255),
	`originalReadingPhysician` varchar(255),
	`dateReviewCompleted` varchar(20),
	`examDos` varchar(20),
	`examIdentifier` varchar(100),
	`examType` varchar(50),
	`origSitus` varchar(100),
	`origCardiacPosition` varchar(100),
	`origLeftHeart` varchar(100),
	`origRightHeart` varchar(100),
	`origEfPercent` varchar(50),
	`origLvWallThickness` varchar(100),
	`origVentricularSeptalDefect` varchar(200),
	`origAtrialSeptalDefect` varchar(200),
	`origPatentForamenOvale` varchar(200),
	`origLvChamberSize` varchar(100),
	`origLaChamberSize` varchar(100),
	`origRvChamberSize` varchar(100),
	`origRaChamberSize` varchar(100),
	`origRegionalWallMotionAbnormalities` varchar(500),
	`origAorticValve` varchar(100),
	`origMitralValve` varchar(100),
	`origTricuspidValve` varchar(100),
	`origPulmonicValve` varchar(100),
	`origAorticStenosis` varchar(100),
	`origAorticInsufficiency` varchar(100),
	`origMitralStenosis` varchar(100),
	`origMitralRegurgitation` varchar(100),
	`origTricuspidStenosis` varchar(100),
	`origTricuspidRegurgitation` varchar(100),
	`origPulmonicStenosis` varchar(100),
	`origPulmonicInsufficiency` varchar(100),
	`origRvspmm` varchar(50),
	`origPericardialEffusion` varchar(100),
	`origPeripheralPulmonaryStenosis` varchar(100),
	`origPulmonaryVeins` varchar(100),
	`origCoronaryAnatomy` varchar(100),
	`origAorticArch` varchar(100),
	`origGreatVessels` varchar(100),
	`origPdaDuctalArch` varchar(100),
	`origConotruncalAnatomy` varchar(100),
	`origRestingEfPercent` varchar(50),
	`origPostStressEfPercent` varchar(50),
	`origRestingRwma` varchar(500),
	`origPostStressRwma` varchar(500),
	`origResponseToStress` varchar(100),
	`origStressAorticStenosis` varchar(100),
	`origStressAorticInsufficiency` varchar(100),
	`origStressMitralStenosis` varchar(100),
	`origStressMitralRegurgitation` varchar(100),
	`origStressTricuspidStenosis` varchar(100),
	`origStressTricuspidRegurgitation` varchar(100),
	`origStressPulmonicStenosis` varchar(100),
	`origStressPulmonicInsufficiency` varchar(100),
	`origStressRvspmm` varchar(50),
	`origFetalBiometry` varchar(100),
	`origFetalPosition` varchar(100),
	`origFetalHeartRateRhythm` varchar(100),
	`concordanceScore` int,
	`discordantFields` text,
	`reviewComments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `physicianComparisonReviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `physicianOverReadInvitations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`labId` int NOT NULL,
	`createdByUserId` int NOT NULL,
	`examIdentifier` varchar(100) NOT NULL,
	`examDos` varchar(20),
	`examType` varchar(50) NOT NULL,
	`postStressDopplerPerformed` varchar(10),
	`originalInterpretingPhysician` varchar(255),
	`reviewerName` varchar(255),
	`reviewerEmail` varchar(320) NOT NULL,
	`accessToken` varchar(128) NOT NULL,
	`accessTokenExpiry` timestamp,
	`status` enum('pending','opened','completed','expired') NOT NULL DEFAULT 'pending',
	`emailSentAt` timestamp,
	`openedAt` timestamp,
	`completedAt` timestamp,
	`submissionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `physicianOverReadInvitations_id` PRIMARY KEY(`id`),
	CONSTRAINT `physicianOverReadInvitations_accessToken_unique` UNIQUE(`accessToken`)
);
--> statement-breakpoint
CREATE TABLE `physicianOverReadSubmissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invitationId` int NOT NULL,
	`labId` int NOT NULL,
	`dateReviewCompleted` varchar(20),
	`examIdentifier` varchar(100),
	`examDos` varchar(20),
	`examType` varchar(50),
	`postStressDopplerPerformed` varchar(10),
	`originalInterpretingPhysician` varchar(255),
	`overReadingPhysicianName` varchar(255),
	`situs` varchar(100),
	`cardiacPosition` varchar(100),
	`leftHeart` varchar(100),
	`rightHeart` varchar(100),
	`efPercent` varchar(50),
	`lvWallThickness` varchar(100),
	`ventricularSeptalDefect` varchar(200),
	`atrialSeptalDefect` varchar(200),
	`patentForamenOvale` varchar(200),
	`lvChamberSize` varchar(100),
	`laChamberSize` varchar(100),
	`rvChamberSize` varchar(100),
	`raChamberSize` varchar(100),
	`regionalWallMotionAbnormalities` varchar(500),
	`aorticValve` varchar(100),
	`mitralValve` varchar(100),
	`tricuspidValve` varchar(100),
	`pulmonicValve` varchar(100),
	`aorticStenosis` varchar(100),
	`aorticInsufficiency` varchar(100),
	`mitralStenosis` varchar(100),
	`mitralRegurgitation` varchar(100),
	`tricuspidStenosis` varchar(100),
	`tricuspidRegurgitation` varchar(100),
	`pulmonicStenosis` varchar(100),
	`pulmonicInsufficiency` varchar(100),
	`rvspmm` varchar(50),
	`pericardialEffusion` varchar(100),
	`peripheralPulmonaryStenosis` varchar(100),
	`pulmonaryVeins` varchar(100),
	`coronaryAnatomy` varchar(100),
	`aorticArch` varchar(100),
	`greatVessels` varchar(100),
	`pdaDuctalArch` varchar(100),
	`conotruncalAnatomy` varchar(100),
	`restingEfPercent` varchar(50),
	`postStressEfPercent` varchar(50),
	`restingRwma` varchar(500),
	`postStressRwma` varchar(500),
	`responseToStress` varchar(100),
	`stressAorticStenosis` varchar(100),
	`stressAorticInsufficiency` varchar(100),
	`stressMitralStenosis` varchar(100),
	`stressMitralRegurgitation` varchar(100),
	`stressTricuspidStenosis` varchar(100),
	`stressTricuspidRegurgitation` varchar(100),
	`stressPulmonicStenosis` varchar(100),
	`stressPulmonicInsufficiency` varchar(100),
	`stressRvspmm` varchar(50),
	`fetalBiometry` varchar(100),
	`fetalPosition` varchar(100),
	`fetalHeartRateRhythm` varchar(100),
	`otherFindings1` text,
	`otherFindings2` text,
	`otherFindings3` text,
	`reviewComments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `physicianOverReadSubmissions_id` PRIMARY KEY(`id`)
);
