CREATE TABLE `possibleCaseStudies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseStudyId` varchar(20) NOT NULL,
	`sourceIqrId` int,
	`examType` varchar(20),
	`examDate` varchar(20),
	`patientMrn` varchar(50),
	`diagnosis` text,
	`clinicalNotes` text,
	`sonographerName` varchar(150),
	`sonographerEmail` varchar(200),
	`interpretingPhysicianName` varchar(150),
	`interpretingPhysicianEmail` varchar(200),
	`accreditationType` varchar(100),
	`submissionStatus` enum('identified','under_review','approved','submitted','rejected') NOT NULL DEFAULT 'identified',
	`submissionNotes` text,
	`labId` int,
	`createdByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `possibleCaseStudies_id` PRIMARY KEY(`id`),
	CONSTRAINT `possibleCaseStudies_caseStudyId_unique` UNIQUE(`caseStudyId`)
);
