ALTER TABLE `imageQualityReviews` ADD `stressStudyType` varchar(100);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `demographicsExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `required2dViews` varchar(20);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `required2dViewsExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `imageOptimized` varchar(20);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `imageOptimizedExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `allMeasurementsObtained` varchar(20);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `allMeasurementsExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `measurements2dExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `measurementPlacementSummary` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `measurementPlacementExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `ventricularFunctionExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `dopplerWaveformExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `forwardFlowExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `dopplerSampleVolumes` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `dopplerSampleVolumesExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `spectralEnvelopeExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `colorFlowExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `colorDopplerExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pulmonaryVeinInflowExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `tapseExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `tissueDopplerExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `aorticValveEval` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `aorticValveExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `lvotSampleVolume` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `lvotSampleVolumeExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `mitralValveEval` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `mitralValveExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pisaEroEval` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pisaEroExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `tricuspidValveEval` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `tricuspidValveExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pulmonicValveEval` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pulmonicValveExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `images2dOptimized` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `images2dOptimizedExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `measurementsAccurateSummary` varchar(50);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `measurementsAccurateExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `dopplerSettingsExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `protocolSequence` varchar(20);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `protocolSequenceExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `pathologyDocumentedExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `clinicalQuestionExplain` text;--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `concordantWithPhysician` varchar(20);--> statement-breakpoint
ALTER TABLE `imageQualityReviews` ADD `concordantExplain` text;